#!/bin/bash
echo
echo Apache2 servisi durduruluyor...
systemctl stop apache2
echo apache2_logs klasörü siliniyor...
rm -rf apache2_logs
echo apache2_logs klasörü oluşturuluyor...
mkdir apache2_logs
echo Apache2 servisi başlatılıyor...
systemctl start apache2
echo Tüm işlemler tamamlandı.
echo
